import { test, expect } from '@playwright/test';
import { getRandomString, getRandomNumber } from '../src/utils/randomData';

test('Admin media release', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByLabel('Email address').click();
  await page.getByLabel('Email address').fill('testadmin@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('bnv8ZMQ@kbd8tah2gta');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Quick Links' }).hover();
  await page.getByRole('link', { name: 'Media Centre' }).click();
  await page.getByRole('button', { name: 'Add New Media Release' }).click();
  const title = getRandomString() + "test";
  await page.getByLabel('Title').fill(title);
  await page.getByLabel('Description').fill(getRandomString() + "test");
  await page.getByLabel('Link').fill(getRandomString() + "test");
  await page.getByLabel('Image').setInputFiles('tests/testdata/testImage.png');
  await page.waitForTimeout(5000);
  await page.getByRole('button', { name: 'Save changes' }).click();
  await expect(page.getByText(title)).toBeVisible();
});

test('Admin Add New Video', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByLabel('Email address').click();
  await page.getByLabel('Email address').fill('testadmin@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('bnv8ZMQ@kbd8tah2gta');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Quick Links' }).hover();
  await page.getByRole('link', { name: 'Knowledge Hub' }).click();
  await page.getByRole('link', { name: 'Add New Video' }).click();
  const title = getRandomString() + "test";
  await page.getByLabel('Title').fill(title);
  await page.getByLabel('Video Description').fill(getRandomString() + "test");
  await page.getByLabel('Youtube Video Link').fill("https://www.youtube.com/watch?v=Iv41XbkORAA&ab_channel=You2Mentor");
  await page.getByLabel('Length of the Video').fill(getRandomNumber(1) + ":" + getRandomNumber(2));
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.waitForTimeout(5000);
  await page.reload();
  await expect(page.getByText(title)).toBeVisible();
});

test('Admin Add New Blog', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByLabel('Email address').click();
  await page.getByLabel('Email address').fill('testadmin@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('bnv8ZMQ@kbd8tah2gta');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Quick Links' }).hover();
  await page.getByRole('link', { name: 'Knowledge Hub' }).click();
  await page.waitForTimeout(5000);
  await page.getByRole('tab', { name: 'Blog' }).click();
  await page.getByRole('link', { name: 'Add New Blog' }).click();
  const title = getRandomString() + "test";
  await page.getByLabel('Title').fill(title);
  await page.getByLabel('Image URL').fill("https://img.freepik.com/premium-vector/job-exam-test-vector-illustration_138676-243.jpg");
  await page.locator('form div').filter({ hasText: 'Blog Post *' }).locator('div').nth(3).fill(getRandomString() + "test");
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.waitForTimeout(5000);
  await page.reload();
  await page.waitForTimeout(5000);
  await page.getByRole('tab', { name: 'Blog' }).click();
  await expect(page.getByText(title)).toBeVisible();
});