name: Lint
on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
