name: Playwright Tests with Bun
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps
    - name: Build Next.js app
      run: bun run build
    - name: Start Next.js server
      run: bun run start & npx wait-on http://localhost:3000
    - name: Run Playwright tests
      run: bunx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30